//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExplodingKittens
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hand
    {
        public int HandID { get; set; }
        public Nullable<int> PlayerID { get; set; }
        public Nullable<int> CardID { get; set; }
    
        public virtual Card Card { get; set; }
        public virtual Player Player { get; set; }
    }
}
